# Generated by Django 5.0.4 on 2024-04-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='is_working',
            field=models.BooleanField(default=False),
        ),
    ]
