# Generated by Django 5.0.4 on 2024-04-17 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_alter_emp_is_working'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp',
            old_name='emp_id',
            new_name='eid',
        ),
    ]
