# Generated by Django 5.0.4 on 2024-04-17 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0004_alter_emp_address_alter_emp_department_alter_emp_eid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp',
            old_name='eid',
            new_name='emp_id',
        ),
    ]
