# Generated by Django 5.0.4 on 2024-04-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0006_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=50)),
                ('feedback', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='emp',
            name='department',
            field=models.CharField(max_length=100),
        ),
    ]
